name: Generate Script

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install ruby-full
          sudo gem install bashly

      - name: Generate bash script
        run: bashly generate
        
      - name: Commit and push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git diff --exit-code || git commit -m 'Run bashly generate' && git push
